config/routes.rb
Imageboard::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :boards do
    resources :nodes
  end

  resources :nodes do
    resources :comments
  end
  
  match '/' => 'boards#index' 

end

app/models/node.rb
class Node < ActiveRecord::Base
  
  validates :body, :picture, :presence => true
  
  has_many :comments, :dependent => :destroy
  belongs_to :board
  mount_uploader :picture, PictureUploader
  
  
  self.per_page = 10 
  
  #def to_param
  #  "#{number}"
  #end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController  
  # GET /nodes
  # GET /nodes.json
  #
  
  layout 'nodes'

  def index  
    @nodes = Node.paginate(:page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @nodes }
    end
  end
  
  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])
    #@node = Node.find_by_number(params[:id], params[:board_id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @node }
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    #@node = Node.find_by_number(params[:id], params[:board_id])
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    respond_to do |format|
      
      @board = Board.find(params[:board_id])
      @node = @board.nodes.create(params[:node])
      if @node.save
        @node.ip = getIp
        @node.last_comment = @node.created_at
        @node.formated_date = @node.created_at.strftime("%d %b %Y, %H:%M")
        @node.number = @board.post_counter.to_int + 1
        @node.save
        @board.post_counter = @node.number
        @board.save
        format.html { redirect_to @node, :notice => 'Node was successfully created.' }
        format.json { render :json => @node, :status => :created, :location => @node }
      else
        # Пока такой костыль.
        format.html { redirect_to @board, :notice => 'There was some errors. Enter a message and coose a picture.' }
        format.json { render :json => @node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    #@node = Node.find_by_number(params[:id], params[:board_id])
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, :notice => 'Node was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @node.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    #@node = Node.find_by_number(params[:id], params[:board_id])
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :ok }
    end
  end

  
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_node.html.haml
%div.thread
  %table
    %tr
      %td= node.head
      %td= link_to 'Reply', node
    %tr
      %td
        %div.picture= link_to( image_tag( node.picture_url(:thumb).to_s), node.picture_url) if node.picture?
        %div=  parser(node.body) #simple_format(markdown(auto_link(node.body)))
  %table
    %td= node.number
    %td= node.created_at.strftime("%d %b %Y, %H:%M")
    %td  Total comments:
    %td= node.comments.size
    -# %td= link_to 'Delete node', node, :confirm => 'Are you sure?', :method => :delete
  
  
  -# Код, выводящий последний комментарий в треде. Да, знаю, что криво >.<
  - if(!node.comments.empty?)
    - if(node.comments.size > 2)
      = render node.comments[node.comments.size - 3]
    - if(node.comments.size > 1 )
      = render node.comments[node.comments.size - 2]
    = render node.comments.last
%hr
%br

app/views/nodes/index.html.haml
%h1 Nodes

= link_to 'New node', new_node_path
%hr
- @nodes.reverse.each do |node|
  %div.thread
    %table
      %tr
        %td= node.head
      %tr
        %td
          %div.picture= link_to( image_tag( node.picture_url(:thumb).to_s), node.picture_url) if node.picture?
          %div.body_text= simple_format(node.body)
    %table
      %td= node.id
      %td= node.board.name
      %td= node.created_at.strftime("%d %b %Y, %H:%M")
      %td  Comments:
      %td= node.comments.size
      %td= link_to 'Reply', node
      %td= #link_to 'Delete node', node, :confirm => 'Are you sure?', :method => :delete     
  %hr
%br
= will_paginate @nodes

app/views/nodes/show.html.haml
%p#notice= notice

%div.thread
  %table 
    %tr
      %td= @node.head
    %tr
      %td
        %div.picture= link_to( image_tag( @node.picture_url(:thumb).to_s), @node.picture_url) if @node.picture?
        %div= parser(@node.body)
  %table    
    %td= @node.number
    %td= @node.created_at.strftime("%d %b %Y, %H:%M")
      
%h2 Comments:

= render @node.comments

%hr
%br

New comment:

= render 'comments/form'

= link_to 'Back', board_path(@node.board)