config/routes.rb
Imageboard::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :boards do
    resources :nodes
  end

  resources :nodes do
    resources :comments
  end
  
  match '/' => 'boards#index' 

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :nodes, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  
  #def to_param
  #  "#{code}"
  #end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # GET /boards
  # GET /boards.json
  #
  layout 'boards'
  def index
    @boards = Board.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    # Пробуем извлекать борду по code
    @board = Board.find(params[:id])
    # Пагинация, аттеншн - располагание тредов по убыванию даты последнего коммента происходит здесь,
    # поэтому нефиг пирать реверс в board/show
    @nodes = @board.nodes.paginate(:page => params[:page], :order => 'last_comment DESC')
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, :notice => 'Board was successfully created.' }
        format.json { render :json => @board, :status => :created, :location => @board }
      else
        format.html { render :action => "new" }
        format.json { render :json => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to @board, :notice => 'Board was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :ok }
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.haml
=form_for ([@board, @board.nodes.build]) do |f|
  .field
    = f.label :head
    = f.text_field :head
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :picture
    = f.file_field :picture
    = f.hidden_field :picture_cache
  .actions
    =f.submit 'Save'                                      

app/views/boards/index.html.haml
%h1 Listing boards

%table.boardlist
  %tr
    %th Name
    %th Code
    %th
    %th

  - @boards.each do |board|
    %tr
      %td= board.name
      %td= board.code
      %td= link_to 'Go', board 
%br

app/views/boards/show.html.haml
%p#notice= notice



%h2
  %center= @board.name
  %center= @board.post_counter
%br
%h2 Nodes:

= render @nodes #reverse в контроллере

New node:

= render 'form'

= will_paginate @nodes

= link_to 'Back', boards_path